job_id: tree-pruner-f1c0ea27-bc52-4764-b632-6c4825178cda
email: patriciakayeduma@u.boisestate.edu
tree_base: birdtree
tree_set: HackettStage2Full
sample_size: 100
names: [Falco_peregrinus, Coragyps_atratus, Cathartes_aura, Falco_columbarius, Pandion_haliaetus,
  Haliaeetus_leucocephalus, Circus_cyaneus, Accipiter_striatus, Accipiter_cooperii,
  Accipiter_gentilis, Buteo_platypterus, Buteo_jamaicensis, Buteo_lagopus, Aquila_chrysaetos,
  Falco_sparverius, Buteo_lineatus]
sample_trees: [HackettStage2Full_3241.tre, HackettStage2Full_8958.tre, HackettStage2Full_2853.tre,
  HackettStage2Full_6068.tre, HackettStage2Full_1557.tre, HackettStage2Full_9044.tre,
  HackettStage2Full_9576.tre, HackettStage2Full_7825.tre, HackettStage2Full_7676.tre,
  HackettStage2Full_0279.tre, HackettStage2Full_9739.tre, HackettStage2Full_3508.tre,
  HackettStage2Full_0804.tre, HackettStage2Full_8195.tre, HackettStage2Full_7413.tre,
  HackettStage2Full_4469.tre, HackettStage2Full_7088.tre, HackettStage2Full_5873.tre,
  HackettStage2Full_1851.tre, HackettStage2Full_0070.tre, HackettStage2Full_2372.tre,
  HackettStage2Full_1335.tre, HackettStage2Full_1432.tre, HackettStage2Full_6070.tre,
  HackettStage2Full_1389.tre, HackettStage2Full_4909.tre, HackettStage2Full_6374.tre,
  HackettStage2Full_5362.tre, HackettStage2Full_7074.tre, HackettStage2Full_0142.tre,
  HackettStage2Full_1988.tre, HackettStage2Full_6139.tre, HackettStage2Full_6787.tre,
  HackettStage2Full_0593.tre, HackettStage2Full_4004.tre, HackettStage2Full_7168.tre,
  HackettStage2Full_7713.tre, HackettStage2Full_2134.tre, HackettStage2Full_9767.tre,
  HackettStage2Full_9464.tre, HackettStage2Full_9087.tre, HackettStage2Full_9606.tre,
  HackettStage2Full_9680.tre, HackettStage2Full_4397.tre, HackettStage2Full_7655.tre,
  HackettStage2Full_9884.tre, HackettStage2Full_3764.tre, HackettStage2Full_2724.tre,
  HackettStage2Full_8090.tre, HackettStage2Full_0692.tre, HackettStage2Full_0376.tre,
  HackettStage2Full_4548.tre, HackettStage2Full_1005.tre, HackettStage2Full_9048.tre,
  HackettStage2Full_8092.tre, HackettStage2Full_5024.tre, HackettStage2Full_8563.tre,
  HackettStage2Full_2685.tre, HackettStage2Full_7246.tre, HackettStage2Full_8345.tre,
  HackettStage2Full_3289.tre, HackettStage2Full_2714.tre, HackettStage2Full_4525.tre,
  HackettStage2Full_6765.tre, HackettStage2Full_6828.tre, HackettStage2Full_0203.tre,
  HackettStage2Full_5999.tre, HackettStage2Full_1312.tre, HackettStage2Full_1283.tre,
  HackettStage2Full_1713.tre, HackettStage2Full_5139.tre, HackettStage2Full_1085.tre,
  HackettStage2Full_8076.tre, HackettStage2Full_5275.tre, HackettStage2Full_0509.tre,
  HackettStage2Full_2483.tre, HackettStage2Full_9788.tre, HackettStage2Full_6337.tre,
  HackettStage2Full_1605.tre, HackettStage2Full_8789.tre, HackettStage2Full_0678.tre,
  HackettStage2Full_4179.tre, HackettStage2Full_2054.tre, HackettStage2Full_8039.tre,
  HackettStage2Full_9896.tre, HackettStage2Full_1512.tre, HackettStage2Full_7877.tre,
  HackettStage2Full_7020.tre, HackettStage2Full_3387.tre, HackettStage2Full_8480.tre,
  HackettStage2Full_5903.tre, HackettStage2Full_2014.tre, HackettStage2Full_7623.tre,
  HackettStage2Full_6468.tre, HackettStage2Full_1803.tre, HackettStage2Full_5270.tre,
  HackettStage2Full_2739.tre, HackettStage2Full_1254.tre, HackettStage2Full_3626.tre,
  HackettStage2Full_2859.tre]
status: COMPLETED
created_at: "2020-07-04T03:53:41Z"
completed_at: "2020-07-04T03:54:39Z"
bad_names: {HackettStage2Full_0070.tre: [], HackettStage2Full_0142.tre: [], HackettStage2Full_0203.tre: [],
  HackettStage2Full_0279.tre: [], HackettStage2Full_0376.tre: [], HackettStage2Full_0509.tre: [],
  HackettStage2Full_0593.tre: [], HackettStage2Full_0678.tre: [], HackettStage2Full_0692.tre: [],
  HackettStage2Full_0804.tre: [], HackettStage2Full_1005.tre: [], HackettStage2Full_1085.tre: [],
  HackettStage2Full_1254.tre: [], HackettStage2Full_1283.tre: [], HackettStage2Full_1312.tre: [],
  HackettStage2Full_1335.tre: [], HackettStage2Full_1389.tre: [], HackettStage2Full_1432.tre: [],
  HackettStage2Full_1512.tre: [], HackettStage2Full_1557.tre: [], HackettStage2Full_1605.tre: [],
  HackettStage2Full_1713.tre: [], HackettStage2Full_1803.tre: [], HackettStage2Full_1851.tre: [],
  HackettStage2Full_1988.tre: [], HackettStage2Full_2014.tre: [], HackettStage2Full_2054.tre: [],
  HackettStage2Full_2134.tre: [], HackettStage2Full_2372.tre: [], HackettStage2Full_2483.tre: [],
  HackettStage2Full_2685.tre: [], HackettStage2Full_2714.tre: [], HackettStage2Full_2724.tre: [],
  HackettStage2Full_2739.tre: [], HackettStage2Full_2853.tre: [], HackettStage2Full_2859.tre: [],
  HackettStage2Full_3241.tre: [], HackettStage2Full_3289.tre: [], HackettStage2Full_3387.tre: [],
  HackettStage2Full_3508.tre: [], HackettStage2Full_3626.tre: [], HackettStage2Full_3764.tre: [],
  HackettStage2Full_4004.tre: [], HackettStage2Full_4179.tre: [], HackettStage2Full_4397.tre: [],
  HackettStage2Full_4469.tre: [], HackettStage2Full_4525.tre: [], HackettStage2Full_4548.tre: [],
  HackettStage2Full_4909.tre: [], HackettStage2Full_5024.tre: [], HackettStage2Full_5139.tre: [],
  HackettStage2Full_5270.tre: [], HackettStage2Full_5275.tre: [], HackettStage2Full_5362.tre: [],
  HackettStage2Full_5873.tre: [], HackettStage2Full_5903.tre: [], HackettStage2Full_5999.tre: [],
  HackettStage2Full_6068.tre: [], HackettStage2Full_6070.tre: [], HackettStage2Full_6139.tre: [],
  HackettStage2Full_6337.tre: [], HackettStage2Full_6374.tre: [], HackettStage2Full_6468.tre: [],
  HackettStage2Full_6765.tre: [], HackettStage2Full_6787.tre: [], HackettStage2Full_6828.tre: [],
  HackettStage2Full_7020.tre: [], HackettStage2Full_7074.tre: [], HackettStage2Full_7088.tre: [],
  HackettStage2Full_7168.tre: [], HackettStage2Full_7246.tre: [], HackettStage2Full_7413.tre: [],
  HackettStage2Full_7623.tre: [], HackettStage2Full_7655.tre: [], HackettStage2Full_7676.tre: [],
  HackettStage2Full_7713.tre: [], HackettStage2Full_7825.tre: [], HackettStage2Full_7877.tre: [],
  HackettStage2Full_8039.tre: [], HackettStage2Full_8076.tre: [], HackettStage2Full_8090.tre: [],
  HackettStage2Full_8092.tre: [], HackettStage2Full_8195.tre: [], HackettStage2Full_8345.tre: [],
  HackettStage2Full_8480.tre: [], HackettStage2Full_8563.tre: [], HackettStage2Full_8789.tre: [],
  HackettStage2Full_8958.tre: [], HackettStage2Full_9044.tre: [], HackettStage2Full_9048.tre: [],
  HackettStage2Full_9087.tre: [], HackettStage2Full_9464.tre: [], HackettStage2Full_9576.tre: [],
  HackettStage2Full_9606.tre: [], HackettStage2Full_9680.tre: [], HackettStage2Full_9739.tre: [],
  HackettStage2Full_9767.tre: [], HackettStage2Full_9788.tre: [], HackettStage2Full_9884.tre: [],
  HackettStage2Full_9896.tre: []}
